version: 2.1

executors:
  general:
    docker:
      - image: cimg/base
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  setup:
    description: 'Set up python environment'
    steps:
      - run: make setup
  lint:
    description: 'Lint Dockerfile and app source'
    steps:
      - run: |
          . /tmp/venv/bin/activate
          make lint-app
  
jobs:
  build-test:
    executor: general
    steps:
      - checkout
      - setup
      - lint
      # Save workspace for subsequent jobs (i.e. test)
      #- persist_to_workspace:
      #    root: .
      #    paths:
      #      - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test