version: 2.1

executors:
  general:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  install-python-deps:
    description: 'Install python dependencies'
    steps:
      - run: make install
  lint:
    description: 'Lint Dockerfile and app source'
    steps:
      - run: make lint-app  
  build-app:
    description: 'Build the Docker container with the app'
    steps:
      - run: make build-app
  test-app:
    description: 'Test application running on local docker container'
    steps:
      - run: make test-app

jobs:
  build-test:
    executor: general
    steps:
      - checkout
      - setup_remote_docker
      - install-python-deps
      - lint
      - build-app
      - test-app
      # Save workspace for subsequent jobs (i.e. test)
      #- persist_to_workspace:
      #    root: .
      #    paths:
      #      - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test