version: 2.1

executors:
  general:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  install-python-deps:
    description: 'Install python dependencies'
    steps:
      - run: make install
  lint:
    description: 'Lint Dockerfile and app source'
    steps:
      - run: make lint-app  

jobs:
  build-test:
    executor: general
    steps:
      - checkout
      - setup_remote_docker
      - install-python-deps
      - lint
      # Save workspace for subsequent jobs (i.e. test)
      #- persist_to_workspace:
      #    root: .
      #    paths:
      #      - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test